version: '2'

services:
  roadrunner:
    build:
      context: ./containers/roadrunner
      args:
        RR_VERSION: ${RR_VERSION}
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
    ports:
      - 8080:8080
    environment:
      RR_VERSION: ${RR_VERSION}
    working_dir: /app
    volumes:
      - .:/var/www/html
      - ./containers/roadrunner/config/.rr.yaml:/etc/rr.yaml:ro
    networks:
      - network
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - network
networks:
  network:
    driver: bridge
volumes:
  mysql:
    driver: local